cache:
  root: ${ETHEREAL_CACHE_ROOT:./.ethereal_cache}

etherscan:
  chain_id: 1
  timeout: 30
  mainnet:
    key: X5QAW799H4EUJ81RB2F6HD5YW1MJUZEJ9Z
  polygon:
    key: GQEHVRGYTSTSG5W6P3FDAWHSVK4NADXKK7
  avalanche:
    key: 4EUFN3TNZKDJFXK8PWCA63QRUHSNDPB2SF
  ftm:
    key: BHMA4EQG19NJ8ZDZWHNID9DRJ2EGN6HQB3
  arbitrum:
    key: HV27JNZG6AF6UEE2F9KEJSD3713SMN3RAP
  optimism:
    key: 9N9DPD2T7FWG8RNWVIH36VM13S6P42898N
